// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          int32              `json:"id"`
	Date        pgtype.Timestamptz `json:"date"`
	Iddevice    int32              `json:"iddevice"`
	Idtypealert int32              `json:"idtypealert"`
}

type Device struct {
	ID               int64            `json:"id"`
	InstallationDate pgtype.Timestamp `json:"installation_date"`
	Room             pgtype.Text      `json:"room"`
	IDPatient        int64            `json:"id_patient"`
}

type Patient struct {
	ID               int64            `json:"id"`
	Name             string           `json:"name"`
	BirthDate        pgtype.Date      `json:"birth_date"`
	Gender           string           `json:"gender"`
	Address          pgtype.Text      `json:"address"`
	EmergencyContact pgtype.Text      `json:"emergency_contact"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type TypeAlert struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type User struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PhoneNumber  pgtype.Text      `json:"phone_number"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	Photo        pgtype.Text      `json:"photo"`
	LastAccess   pgtype.Timestamp `json:"last_access"`
}

type UserPatient struct {
	IDUser    int64 `json:"id_user"`
	IDPatient int64 `json:"id_patient"`
}
