// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alert (
    iddevice, idtypealert
) VALUES ($1, $2) RETURNING id, date, iddevice, idtypealert
`

type CreateAlertParams struct {
	Iddevice    int32 `json:"iddevice"`
	Idtypealert int32 `json:"idtypealert"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert, arg.Iddevice, arg.Idtypealert)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Iddevice,
		&i.Idtypealert,
	)
	return i, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patient (
    name,birth_date, gender, address,emergency_contact)
    VALUES ($1, $2, $3, $4, $5) RETURNING id, name, birth_date, gender, address, emergency_contact, created_at
`

type CreatePatientParams struct {
	Name             string      `json:"name"`
	BirthDate        pgtype.Date `json:"birth_date"`
	Gender           string      `json:"gender"`
	Address          pgtype.Text `json:"address"`
	EmergencyContact pgtype.Text `json:"emergency_contact"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.Name,
		arg.BirthDate,
		arg.Gender,
		arg.Address,
		arg.EmergencyContact,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.Gender,
		&i.Address,
		&i.EmergencyContact,
		&i.CreatedAt,
	)
	return i, err
}

const createTypeAlert = `-- name: CreateTypeAlert :one
INSERT INTO type_alert (
    id, description
) VALUES ($1, $2) RETURNING id, description
`

type CreateTypeAlertParams struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

func (q *Queries) CreateTypeAlert(ctx context.Context, arg CreateTypeAlertParams) (TypeAlert, error) {
	row := q.db.QueryRow(ctx, createTypeAlert, arg.ID, arg.Description)
	var i TypeAlert
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, installation_date, room, id_patient FROM device
WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.InstallationDate,
		&i.Room,
		&i.IDPatient,
	)
	return i, err
}

const getTypeAlertByID = `-- name: GetTypeAlertByID :one
SELECT id, description FROM type_alert
WHERE id = $1
`

func (q *Queries) GetTypeAlertByID(ctx context.Context, id int32) (TypeAlert, error) {
	row := q.db.QueryRow(ctx, getTypeAlertByID, id)
	var i TypeAlert
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT
    a.id,
    a.date,
    a.iddevice,
    a.idtypealert,
    ta.description AS alert_type_description
FROM alert a
         JOIN device d ON a.iddevice = d.id
         JOIN type_alert ta ON a.idtypealert = ta.id
ORDER BY a.date DESC
`

type ListAlertsRow struct {
	ID                   int32              `json:"id"`
	Date                 pgtype.Timestamptz `json:"date"`
	Iddevice             int32              `json:"iddevice"`
	Idtypealert          int32              `json:"idtypealert"`
	AlertTypeDescription string             `json:"alert_type_description"`
}

func (q *Queries) ListAlerts(ctx context.Context) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Iddevice,
			&i.Idtypealert,
			&i.AlertTypeDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByPatient = `-- name: ListAlertsByPatient :many
SELECT
    a.id,
    a.date,
    a.iddevice,
    a.idtypealert,
    ta.description AS alert_type_description
FROM alert a
         JOIN device d ON a.iddevice = d.id
         JOIN type_alert ta ON a.idtypealert = ta.id
WHERE d.id_patient = $1
ORDER BY a.date DESC
`

type ListAlertsByPatientRow struct {
	ID                   int32              `json:"id"`
	Date                 pgtype.Timestamptz `json:"date"`
	Iddevice             int32              `json:"iddevice"`
	Idtypealert          int32              `json:"idtypealert"`
	AlertTypeDescription string             `json:"alert_type_description"`
}

func (q *Queries) ListAlertsByPatient(ctx context.Context, idPatient int64) ([]ListAlertsByPatientRow, error) {
	rows, err := q.db.Query(ctx, listAlertsByPatient, idPatient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsByPatientRow
	for rows.Next() {
		var i ListAlertsByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Iddevice,
			&i.Idtypealert,
			&i.AlertTypeDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatients = `-- name: ListPatients :many
SELECT id, name, birth_date, gender, address, emergency_contact, created_at FROM patient
ORDER BY name ASC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BirthDate,
			&i.Gender,
			&i.Address,
			&i.EmergencyContact,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypeAlerts = `-- name: ListTypeAlerts :many
SELECT id, description FROM type_alert
ORDER BY id DESC
`

func (q *Queries) ListTypeAlerts(ctx context.Context) ([]TypeAlert, error) {
	rows, err := q.db.Query(ctx, listTypeAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TypeAlert
	for rows.Next() {
		var i TypeAlert
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
