// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alert (
    iddevice, idtypealert
) VALUES ($1, $2) RETURNING id, date, iddevice, idtypealert
`

type CreateAlertParams struct {
	Iddevice    int32 `json:"iddevice"`
	Idtypealert int32 `json:"idtypealert"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert, arg.Iddevice, arg.Idtypealert)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Iddevice,
		&i.Idtypealert,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, installation_date, room, id_patient FROM device
WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.InstallationDate,
		&i.Room,
		&i.IDPatient,
	)
	return i, err
}

const getTypeAlertByID = `-- name: GetTypeAlertByID :one
SELECT id, description FROM type_alert
WHERE id = $1
`

func (q *Queries) GetTypeAlertByID(ctx context.Context, id int32) (TypeAlert, error) {
	row := q.db.QueryRow(ctx, getTypeAlertByID, id)
	var i TypeAlert
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, date, iddevice, idtypealert FROM alert
ORDER BY date DESC
`

func (q *Queries) ListAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Iddevice,
			&i.Idtypealert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
